# Generated by Django 5.0 on 2023-12-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoriaingreso',
            name='ActividadCine',
            field=models.BooleanField(default=False, verbose_name='Cine'),
        ),
        migrations.AddField(
            model_name='tutoriaingreso',
            name='ActividadConciertos',
            field=models.BooleanField(default=False, verbose_name='Conciertos'),
        ),
        migrations.AddField(
            model_name='tutoriaingreso',
            name='ActividadDeporte',
            field=models.BooleanField(default=False, verbose_name='Deporte'),
        ),
        migrations.AddField(
            model_name='tutoriaingreso',
            name='ActividadFeriasCulturales',
            field=models.BooleanField(default=False, verbose_name='Ferias culturales'),
        ),
        migrations.AddField(
            model_name='tutoriaingreso',
            name='ActividadLeerLibros',
            field=models.BooleanField(default=False, verbose_name='Leer Libros'),
        ),
        migrations.AddField(
            model_name='tutoriaingreso',
            name='ActividadMuseos',
            field=models.BooleanField(default=False, verbose_name='Museos'),
        ),
        migrations.AddField(
            model_name='tutoriaingreso',
            name='ActividadOtro',
            field=models.CharField(default='', max_length=150),
        ),
    ]
