# Generated by Django 5.0 on 2024-01-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tutoriaingreso_actividadcine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adicciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoke', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=1, verbose_name='¿Fumas?')),
                ('w_smoke', models.IntegerField(choices=[(0, 'Tabaco'), (1, 'Marihuana'), (2, 'Otro: ')], default=0, verbose_name='¿Si la respuesta es si, qué es lo que fumas?')),
                ('other_smoke', models.CharField(max_length=150, verbose_name='')),
                ('t_smoke', models.IntegerField(choices=[(0, 'De 1 a 3'), (1, 'De 3 a 5'), (2, 'De 5 a 10'), (3, 'Mas de 10'), (4, 'Ocasionalmente')], default=0, verbose_name='Si la respuesta es si, ¿Cuántas dosis al día?')),
                ('drinks_alcohol', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=1, verbose_name='¿Consumes bebidas con alcohol?')),
                ('t_alcohol', models.IntegerField(choices=[(0, 'Diario'), (1, 'Una o dos veces por semana'), (2, 'Mas de 2 veces por semana')], default=0, verbose_name='Si la respuesta es si, ¿Con qué frecuencia?')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recomendacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('Plan_de_Estudios', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('Planta_Academica', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('Instalaciones', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('Costos', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('Horarios', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('Prestigio_Institucion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('Reconocimiento_social_familiar', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('Superacion_personal', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('Actualizacion_campo_laboral', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('Movilidad_laboral_e_ingresos', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('Empresas_solicitan_grado_academico', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=1)),
                ('cinema', models.BooleanField(default=False, verbose_name='Cine')),
                ('museum', models.BooleanField(default=False, verbose_name='Museos')),
                ('concerts', models.BooleanField(default=False, verbose_name='Conciertos')),
                ('reading', models.BooleanField(default=False, verbose_name='Leer libros')),
                ('cultural_fairs', models.BooleanField(default=False, verbose_name='Ferias Culturales')),
                ('sports', models.BooleanField(default=False, verbose_name='Deportes')),
                ('others', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleoIngresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrabajoActual', models.BooleanField(choices=[(1, 'Si'), (0, 'No')], default=0, verbose_name='¿Trabajas actualmente?')),
                ('TrabajoRelacionadoCarrera', models.BooleanField(choices=[(1, 'Si'), (0, 'No')], default=0, verbose_name='¿Tu trabajo actual esta relacionado con la carrera que estudias?')),
                ('HorasTrabajadasSemana', models.BooleanField(choices=[(0, 'Menos de 10'), (1, 'De 10 a 20'), (2, 'De 21 a 40')], default=0, verbose_name='¿Trabajas actualmente?')),
                ('IngresoMensualTrabajo', models.BooleanField(choices=[(0, '$2,600 a $6,000'), (1, '$6,001 a $10,000'), (2, '10,001 a $32,000'), (3, '32,001 a $81,000'), (4, 'Mas de $81,000')], default=0, verbose_name='Por favor indica a cuanto asciende tu ingreso mensual aproximadamente si trabajas:')),
                ('AportacionEconomicaImportancia', models.BooleanField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Senala que tan importante es su aportacion economica en tu hogar a partir de la siguiente escala:')),
            ],
        ),
        migrations.CreateModel(
            name='emprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_emprendimiento', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=1, verbose_name='¿Tienes alguna idea o proyecto de emprendimieto?')),
                ('is_interesting', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, verbose_name='¿Te interesa emprender?')),
                ('if_option', models.IntegerField(choices=[(1, 'Tengo una idea de negocio que me gustaria impulsar'), (2, 'Estoy desarollando un proyecto de emprendimiento, pero no lo he puesto en marcha'), (3, 'Ninguna de las anteriores')], default=1, verbose_name='Si respondiste si a la pregunta anterior, por favor, selecciona la opcion de acuerdo con tu situación')),
                ('tools_udg', models.BooleanField(choices=[(1, 'Si'), (0, 'No')], default=0, verbose_name='¿Conoces las herramientas que la U de G ofrece para desarrollar y dar seguimiento a tu emprendimiento?')),
                ('is_community', models.BooleanField(choices=[(1, 'Si'), (0, 'No')], default=0, verbose_name='¿Te interesaria formar parte de alguna comunidad de emprendimiento para seguir desarrollando tus habilidades?')),
            ],
        ),
        migrations.RenameField(
            model_name='tutoriaingreso',
            old_name='pregunta_radio',
            new_name='Recomendacion',
        ),
        migrations.RemoveField(
            model_name='tutoriaingreso',
            name='ActividadCine',
        ),
        migrations.RemoveField(
            model_name='tutoriaingreso',
            name='ActividadConciertos',
        ),
        migrations.RemoveField(
            model_name='tutoriaingreso',
            name='ActividadDeporte',
        ),
        migrations.RemoveField(
            model_name='tutoriaingreso',
            name='ActividadFeriasCulturales',
        ),
        migrations.RemoveField(
            model_name='tutoriaingreso',
            name='ActividadLeerLibros',
        ),
        migrations.RemoveField(
            model_name='tutoriaingreso',
            name='ActividadMuseos',
        ),
        migrations.RemoveField(
            model_name='tutoriaingreso',
            name='ActividadOtro',
        ),
    ]
