# Generated by Django 5.0 on 2024-01-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adicciones_educationalprogram_empleoingresos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='e_tiemposTrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_trns', models.IntegerField(choices=[(0, 'Un solo medio de transporte público'), (1, 'Dos o más medios de transporte público'), (2, 'Automóvil'), (3, 'Bicicleta'), (4, 'Taxi'), (5, 'Uber'), (6, 'Otro')], default=0, verbose_name='¿Qué medio de transporte utilizas regularmente para trasladarte a CUCEI?')),
                ('otro_trns', models.CharField(max_length=150, verbose_name='')),
                ('timetransport', models.IntegerField(choices=[(0, 'De 15 a 30 minutos'), (1, 'De 31 a 45 minutos'), (2, 'De 46 a 60 minutos'), (3, 'De 61 minutos a 2 horas'), (4, 'Más de dos horas')], default=0, verbose_name='¿Cuánto tiempo aproximadamente te toma llegar diario a CUCEI desde tu casa?')),
            ],
        ),
        migrations.CreateModel(
            name='e_vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable_ecnm', models.IntegerField(choices=[(0, 'Yo'), (1, 'Madre'), (2, 'Padre'), (3, 'Madre y Padre'), (4, 'Tutor legal'), (5, 'Hermanos, hermanas'), (6, 'Pareja'), (7, 'Otros')], default=0, verbose_name='En tu hogar donde vives actualmente, ¿Quién es la persona responsable del mayor aporte económico?')),
                ('viveAct', models.IntegerField(choices=[(0, 'Sola/Solo'), (1, 'Pareja'), (2, 'Padres'), (3, 'En casa de asistencia o compartiendo vivienda con otras personas'), (4, 'Otro')], default=0, verbose_name='¿Con quién vives actualmente?')),
                ('otro_vive', models.CharField(max_length=150, verbose_name='')),
                ('apoyo_economico', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, verbose_name='¿Recibes algún apoyo económico? (como becas, subsidio, etc)')),
                ('is_foraneo', models.CharField(max_length=400, verbose_name='¿Eres foráneo? (Si la respuesta es Si especifica de que estado procedes)')),
            ],
        ),
    ]
