# Generated by Django 5.0 on 2024-01-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_e_tiempostrs_e_vivienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='maccesotics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.BooleanField(default=False, verbose_name='Computadora')),
                ('telefono', models.BooleanField(default=False, verbose_name='Télefono inteligente')),
                ('tableta', models.BooleanField(default=False, verbose_name='Tableta')),
                ('ninguno', models.BooleanField(default=False, verbose_name='Ninguno de los anteriores')),
                ('internet', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=1, verbose_name='¿Cuentas con internet propio?')),
                ('lugar_estudio', models.CharField(max_length=100, verbose_name='')),
                ('horas', models.CharField(max_length=100, verbose_name='')),
                ('nmaterias', models.CharField(max_length=10, verbose_name='')),
                ('horasclases', models.CharField(max_length=10, verbose_name='')),
                ('horaslibres', models.CharField(max_length=10, verbose_name='')),
                ('perfil', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=1, verbose_name='¿Conoces el perfil de egreso de tu programa educativo?')),
                ('malla', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=1, verbose_name='¿Conoces la malla curricular de tu programa educativo?')),
                ('materias_pre', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=1, verbose_name='¿Sabes que materias llevan pre-requisito en tu malla curricular')),
            ],
        ),
        migrations.CreateModel(
            name='mdiscapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_discapacidad', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, verbose_name='¿Tienes alguna discapacidad?')),
                ('tipod', models.CharField(max_length=150, verbose_name='')),
                ('dispositivo_d', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, verbose_name='¿Usas o necesitas algún tipo de dispositivos de asistencia? Por ejemplo: silla de ruedas, bastones, muletas, prótesis, audífonos, etc.')),
                ('tipodispositivod', models.CharField(max_length=150, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='mneurodiversidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoNeurodiversidad', models.CharField(choices=[('Autismo', 'Autismo: transtorno del desarrollo que se incluye dentro del espectro autista y que afecta la interacción social recíproca, la comunicaión verbal y no verbal, una resistencia para aceptar el cambio, inflexibilidad del pensamiento así como poseer campos de interés estrechos y absorbentes'), ('Asperger', 'Asperger: transtorno del desarrollo que se incluye dentro del espectro autista y que afecta la interacción social recíproca, la comunicación verbal y no verbal, una resistencia para aceptar el cambio, inflexibilidad del pensamiento así como poseer campos de interés estrechos y absorbentes.'), ('Discalculia', 'Discalculia: dificulta la comprensión de las matemáticas y las tareas relacionadas.'), ('Dislexia', 'Dislexia: dificultad en la lectura debido a inconvenientes para identificar los sonidos del habla y aprender a relacionarlos con las letras y las palabras'), ('Dispraxia', 'Dispraxia: trastorno psicomotriz que se da en la infancia y hace que los movimientos que requieren la movilización y coordinación de varios grupos musculares'), ('Hiperactividad', 'Trastorno por Déficit de Atención e Hiperactividad: problemas para prestar atención, controlar conductas impulsivas (podrían actuar sin pensar en el resultado de sus acciones) o pueden ser demasiados activos'), ('Tourette', 'Síndrome de Tourette: se caracteriza por muchos tics motores y fónicos que perduran durante más de un año.'), ('No', 'No'), ('Otro', 'Otro: ')], default='No', max_length=150, verbose_name='¿Consideras que te encuentras en una de las siguientes condiciones de neurodiversidad? :')),
                ('otrotipo_neuro', models.CharField(max_length=150, verbose_name='')),
                ('diagnostico', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, verbose_name='¿Tienes diágnostico de un médico?')),
                ('tratamiento', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, verbose_name='En caso de haber contestado SI a la pregunta anterior, ¿Estás en tratamiento?')),
                ('zurdo', models.BooleanField(default=False, verbose_name='Soy zurda/zurdo')),
                ('enfermedad_celiaca', models.BooleanField(default=False, verbose_name='Enfermedad celíaca (alergía al gluten)')),
                ('talla_baja', models.BooleanField(default=False, verbose_name='Soy persona de talla baja')),
                ('is_not', models.BooleanField(default=False, verbose_name='No')),
            ],
        ),
        migrations.CreateModel(
            name='mpersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunidadlgbt', models.IntegerField(choices=[(1, 'Si'), (0, 'No'), (2, 'Prefiero no decirlo')], default=0, verbose_name='¿Perteneces a una comunidad LGBTTTIQ+?')),
                ('identidadGen', models.IntegerField(choices=[(1, 'Cisgénero'), (2, 'Transgénero'), (3, 'Transexual'), (4, 'No Binario'), (5, 'Prefiero no responder'), (6, 'Otro: ')], default=1, verbose_name='Identidad de Genéro')),
                ('other_identidad', models.CharField(max_length=150, verbose_name='')),
                ('hijos', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, verbose_name='¿Tienes hijos?')),
                ('hijoscuidado', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, verbose_name='¿Están a tu cuidado hijos u otros menores?')),
                ('avanzcuidado', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, verbose_name='¿Cuidas de una persona en edad avanzada, enfermo o con capacidades diferentes?')),
            ],
        ),
        migrations.CreateModel(
            name='mpueblos_orig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunidad', models.CharField(max_length=150, verbose_name='')),
                ('lengua', models.CharField(max_length=150, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='msalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiposangre', models.CharField(choices=[('AB+', 'AB+'), ('AB-', 'AB-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('Otro', 'Otro: ')], default='O-', max_length=100, verbose_name='Tipo de Sangre: ')),
                ('otro_sangre', models.CharField(max_length=10, verbose_name='')),
                ('enfermedad_salud', models.CharField(max_length=100, verbose_name='')),
                ('alergias', models.CharField(max_length=100, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='msaludmental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suenio', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Algunas veces'), (3, 'Frecuentemente'), (4, 'Casi siempre'), (5, 'Siempre')], default=1, verbose_name='Dificultades para conciliar el sueño')),
                ('cansancio', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Algunas veces'), (3, 'Frecuentemente'), (4, 'Casi siempre'), (5, 'Siempre')], default=1, verbose_name='Cansancio o fatiga que te impiden realizar algunas actividades')),
                ('fobias', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Algunas veces'), (3, 'Frecuentemente'), (4, 'Casi siempre'), (5, 'Siempre')], default=1, verbose_name='Miedos incontrolables o fobias a objetos, personas o situaciones')),
                ('irritacion', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Algunas veces'), (3, 'Frecuentemente'), (4, 'Casi siempre'), (5, 'Siempre')], default=1, verbose_name='Irritación o mal humor')),
                ('ansiedad', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Algunas veces'), (3, 'Frecuentemente'), (4, 'Casi siempre'), (5, 'Siempre')], default=1, verbose_name='Ansiedad o angustia generalizada que te impide concentrarte')),
                ('motivacion', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Algunas veces'), (3, 'Frecuentemente'), (4, 'Casi siempre'), (5, 'Siempre')], default=1, verbose_name='Motivación para hacer tus actividades cotidianas')),
                ('pensamientos', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Algunas veces'), (3, 'Frecuentemente'), (4, 'Casi siempre'), (5, 'Siempre')], default=1, verbose_name='Pensamientos sobre quitarte la vida')),
                ('tristeza', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Algunas veces'), (3, 'Frecuentemente'), (4, 'Casi siempre'), (5, 'Siempre')], default=1, verbose_name='Experimento tristeza')),
                ('felicidad', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Algunas veces'), (3, 'Frecuentemente'), (4, 'Casi siempre'), (5, 'Siempre')], default=1, verbose_name='En general, me siento feliz')),
                ('terapia', models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, verbose_name='¿Acudes a terapia psicológica o tratamiento psiquiátrico?')),
            ],
        ),
        migrations.AlterField(
            model_name='adicciones',
            name='drinks_alcohol',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, verbose_name='¿Consumes bebidas con alcohol?'),
        ),
        migrations.AlterField(
            model_name='adicciones',
            name='smoke',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0, verbose_name='¿Fumas?'),
        ),
        migrations.AlterField(
            model_name='adicciones',
            name='t_alcohol',
            field=models.IntegerField(choices=[(1, 'Diario'), (2, 'Una o dos veces por semana'), (3, 'Mas de 2 veces por semana')], default=1, verbose_name='Si la respuesta es si, ¿Con qué frecuencia?'),
        ),
        migrations.AlterField(
            model_name='adicciones',
            name='t_smoke',
            field=models.IntegerField(choices=[(1, 'De 1 a 3'), (2, 'De 3 a 5'), (3, 'De 5 a 10'), (4, 'Mas de 10'), (5, 'Ocasionalmente')], default=1, verbose_name='Si la respuesta es si, ¿Cuántas dosis al día?'),
        ),
        migrations.AlterField(
            model_name='adicciones',
            name='w_smoke',
            field=models.IntegerField(choices=[(1, 'Tabaco'), (2, 'Marihuana'), (3, 'Otro: ')], default=1, verbose_name='¿Si la respuesta es si, qué es lo que fumas?'),
        ),
        migrations.AlterField(
            model_name='e_tiempostrs',
            name='medio_trns',
            field=models.IntegerField(choices=[(1, 'Un solo medio de transporte público'), (2, 'Dos o más medios de transporte público'), (3, 'Automóvil'), (4, 'Bicicleta'), (5, 'Taxi'), (6, 'Uber'), (7, 'Otro')], default=1, verbose_name='¿Qué medio de transporte utilizas regularmente para trasladarte a CUCEI?'),
        ),
        migrations.AlterField(
            model_name='e_tiempostrs',
            name='timetransport',
            field=models.IntegerField(choices=[(1, 'De 15 a 30 minutos'), (2, 'De 31 a 45 minutos'), (3, 'De 46 a 60 minutos'), (4, 'De 61 minutos a 2 horas'), (5, 'Más de dos horas')], default=1, verbose_name='¿Cuánto tiempo aproximadamente te toma llegar diario a CUCEI desde tu casa?'),
        ),
        migrations.AlterField(
            model_name='e_vivienda',
            name='responsable_ecnm',
            field=models.IntegerField(choices=[(1, 'Yo'), (2, 'Madre'), (3, 'Padre'), (4, 'Madre y Padre'), (5, 'Tutor legal'), (6, 'Hermanos, hermanas'), (7, 'Pareja'), (8, 'Otros')], default=1, verbose_name='En tu hogar donde vives actualmente, ¿Quién es la persona responsable del mayor aporte económico?'),
        ),
        migrations.AlterField(
            model_name='e_vivienda',
            name='viveAct',
            field=models.IntegerField(choices=[(1, 'Sola/Solo'), (2, 'Pareja'), (3, 'Padres'), (4, 'En casa de asistencia o compartiendo vivienda con otras personas'), (5, 'Otro')], default=1, verbose_name='¿Con quién vives actualmente?'),
        ),
        migrations.AlterField(
            model_name='empleoingresos',
            name='AportacionEconomicaImportancia',
            field=models.BooleanField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Senala que tan importante es su aportacion economica en tu hogar a partir de la siguiente escala:'),
        ),
        migrations.AlterField(
            model_name='empleoingresos',
            name='HorasTrabajadasSemana',
            field=models.BooleanField(choices=[(1, 'Menos de 10'), (2, 'De 10 a 20'), (3, 'De 21 a 40')], default=1, verbose_name='¿Trabajas actualmente?'),
        ),
        migrations.AlterField(
            model_name='empleoingresos',
            name='IngresoMensualTrabajo',
            field=models.BooleanField(choices=[(1, '$2,600 a $6,000'), (2, '$6,001 a $10,000'), (3, '10,001 a $32,000'), (4, '32,001 a $81,000'), (5, 'Mas de $81,000')], default=1, verbose_name='Por favor indica a cuanto asciende tu ingreso mensual aproximadamente si trabajas:'),
        ),
        migrations.AlterField(
            model_name='tutoriaingreso',
            name='EstadoCivil',
            field=models.IntegerField(choices=[(1, 'Soltero/Soltera'), (2, 'Matrimonio'), (3, 'Union Libre'), (4, 'Viudez')]),
        ),
        migrations.AlterField(
            model_name='tutoriaingreso',
            name='Genero',
            field=models.IntegerField(choices=[(1, 'Hombre'), (2, 'Mujer'), (3, 'Prefiero no decirlo'), (4, 'No binario')]),
        ),
        migrations.AlterField(
            model_name='tutoriaingreso',
            name='ProgramaEducativo',
            field=models.IntegerField(choices=[(1, 'Ingenieria en Computacion'), (2, 'Ingenieria en Informatica')]),
        ),
    ]
