# Generated by Django 5.0 on 2024-01-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_maccesotics_mdiscapacidad_mneurodiversidad_mpersonal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maccesotics',
            name='estilos_aprendizaje',
            field=models.IntegerField(choices=[(2, 'Auditivo: Estilo se orienta más hacia la asimilación de información a través del oído, depende de escuchar y hablar como maneras principales para su aprendizaje, estas personas dialogan tanto como interna como externamente.'), (1, 'Visual: Ocurre cuando uno tiende a pensar en imágenes y a relacionarlas con ideas y conceptos. Como por ejemplo cuando uno recurre a mapas conceptuales para recordar ideas, conceptos y procesos complejos. Por lo mismo, éste sistema está directamente relacionado con nuestra capacidad de abstracción y planificación.'), (3, 'Knestésico: En otras palabras, es lo que ocurre cuando aprendemos más fácilmente al movernos y tocar las cosas, como cuando caminamos al recitar información o hacemos un experimento manipulando instrumentos de laboratorio.')], default=1, verbose_name=''),
        ),
    ]
