# Generated by Django 5.0 on 2024-01-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_maccesotics_estilos_aprendizaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalprogram',
            name='Actualizacion_campo_laboral',
            field=models.IntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, ''), (6, '')], default=1),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='Costos',
            field=models.IntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, ''), (6, '')], default=1),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='Empresas_solicitan_grado_academico',
            field=models.IntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, ''), (6, '')], default=1),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='Horarios',
            field=models.IntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, ''), (6, '')], default=1),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='Instalaciones',
            field=models.IntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, ''), (6, '')], default=1),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='Movilidad_laboral_e_ingresos',
            field=models.IntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, ''), (6, '')], default=1),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='Plan_de_Estudios',
            field=models.IntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, ''), (6, '')], default=1),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='Planta_Academica',
            field=models.IntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, ''), (6, '')], default=1),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='Prestigio_Institucion',
            field=models.IntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, ''), (6, '')], default=1),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='Recomendacion',
            field=models.IntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, ''), (6, '')], default=1),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='Reconocimiento_social_familiar',
            field=models.IntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, ''), (6, '')], default=1),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='Superacion_personal',
            field=models.IntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, ''), (6, '')], default=1),
        ),
    ]
