# Generated by Django 5.0 on 2024-01-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estudiante', models.IntegerField()),
                ('id_tutor', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('status', models.IntegerField()),
                ('calendario', models.CharField(max_length=20)),
                ('motivo', models.TextField()),
            ],
        ),
    ]
