# Generated by Django 5.0 on 2024-01-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estudiante', models.IntegerField()),
                ('id_tutor', models.IntegerField()),
                ('titulo', models.TextField()),
                ('situacion', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='asesoria',
        ),
    ]
