# Generated by Django 5.0 on 2024-02-04 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalcore', '0002_reporte_delete_asesoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='id_estudiante',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='id_tutor',
        ),
        migrations.CreateModel(
            name='sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Nombre: ')),
                ('fecha', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Abierta'), ('Close', 'Finalizada'), ('Canceled', 'Cancelada')], default=1, max_length=100)),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], max_length=50)),
                ('comentarios', models.TextField(verbose_name='')),
                ('sitio', models.CharField(max_length=150, verbose_name='')),
                ('hora', models.TimeField()),
                ('user_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
