# Generated by Django 5.0 on 2024-01-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre: ')),
                ('apellido_m', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('apellido_p', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('carrera', models.CharField(choices=[('LFI', 'Licenciatura en Fisica'), ('LMT', 'Licenciatura en Matematicas'), ('INNI', 'Ingenieria en Informatica'), ('INCO', 'Ingenieria en Computacion'), ('QFB', 'Quimico Farmaceutico Biólogo')], default='LFI', max_length=100, verbose_name='Selecciona carrera: ')),
                ('dia', models.CharField(max_length=2)),
                ('mes', models.CharField(max_length=2)),
                ('anio', models.CharField(max_length=2, verbose_name='Año')),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=10)),
                ('estadocivil', models.IntegerField(choices=[(1, 'Soltero/Soltera'), (2, 'Matrimonio'), (3, 'Union Libre'), (4, 'Viudez')], default=1)),
                ('sexo', models.IntegerField(choices=[(1, 'Hombre'), (2, 'Mujer'), (3, 'Prefiero no decirlo'), (4, 'No binario')], default=1)),
                ('municipio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_udg', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('rol', models.IntegerField()),
                ('activo', models.BooleanField()),
                ('fecha_registro', models.CharField(max_length=8)),
            ],
        ),
    ]
