# Generated by Django 5.0 on 2024-01-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre: ')),
                ('apellido_m', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('apellido_p', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('coordinacion_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ciclo_actual',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ciclo_ingreso',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
