# Generated by Django 5.0 on 2024-01-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tutor_estudiante_ciclo_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre: ')),
            ],
        ),
        migrations.CreateModel(
            name='programaEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre: ')),
                ('correo', models.CharField(max_length=100, verbose_name='Nombre: ')),
            ],
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='id',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='coordinacion_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='codigo_udg',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='codigo_udg',
            field=models.CharField(default='default', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
