# Generated by Django 5.0 on 2024-01-14 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_division_programaeducativo_remove_estudiante_anio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario'),
            preserve_default=False,
        ),
    ]
