# Generated by Django 5.0 on 2024-01-15 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_estudiante_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='estudianteM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo_admision', models.CharField(default='', max_length=3, verbose_name='')),
                ('ciclo_actual', models.CharField(default='', max_length=3, verbose_name='')),
                ('telefono', models.CharField(max_length=10, verbose_name='')),
                ('asesorado', models.BooleanField(default=False)),
                ('residencia', models.CharField(max_length=150, verbose_name='')),
                ('estado_civil', models.IntegerField(choices=[(1, 'Soltero/Soltera'), (2, 'Matrimonio'), (3, 'Union Libre'), (4, 'Viudez')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='tutorM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumnos_n', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='usuarioM',
            fields=[
                ('codigo_udg', models.CharField(default='default', max_length=10, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('rol', models.IntegerField()),
                ('nombre', models.CharField(max_length=100, verbose_name='')),
                ('apellido_m', models.CharField(max_length=100, verbose_name='')),
                ('apellido_p', models.CharField(max_length=100, verbose_name='')),
                ('fecha_nacimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('sexo', models.IntegerField(choices=[(1, 'Hombre'), (2, 'Mujer'), (3, 'Prefiero no decirlo'), (4, 'No binario')], default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='tutor',
        ),
        migrations.AddField(
            model_name='tutorm',
            name='codigo_udg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuariom'),
        ),
        migrations.AddField(
            model_name='estudiantem',
            name='codigo_udg',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='accounts.usuariom'),
        ),
        migrations.DeleteModel(
            name='estudiante',
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
