# Generated by Django 5.0 on 2024-01-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_tutormodel_tutor_rename_usuariomodel_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.BooleanField(default=False),
        ),
    ]
