# Generated by Django 5.0 on 2024-01-30 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_tutor_codigo_udg_remove_tutor_division_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('materia', models.IntegerField(choices=[(1, 'Programacion'), (2, 'Calculo'), (3, 'Pre calculo'), (4, 'Fisica'), (5, 'Algoritmia')])),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asesoria_alumno', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asesoria_tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
