# Generated by Django 5.0 on 2024-02-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_asesoria_materia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asesoria',
            old_name='descripcion',
            new_name='motivos',
        ),
        migrations.RemoveField(
            model_name='asesoria',
            name='materia',
        ),
        migrations.AddField(
            model_name='asesoria',
            name='status',
            field=models.CharField(choices=[('Inicio', 'Inicio'), ('Trayecto', 'Trayecto'), ('Egreso', 'Egreso')], default='Solicitada', max_length=20),
        ),
        migrations.AddField(
            model_name='asesoria',
            name='tipo',
            field=models.CharField(choices=[('Inicio', 'Inicio'), ('Trayecto', 'Trayecto'), ('Egreso', 'Egreso')], default='Inicio', max_length=20),
        ),
    ]
