# Generated by Django 5.0 on 2024-02-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_asesoria_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estudiante', models.IntegerField()),
                ('id_tutor', models.IntegerField()),
                ('titulo', models.TextField()),
                ('situacion', models.TextField()),
            ],
        ),
    ]
