# Generated by Django 5.0 on 2024-02-05 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_reporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='id_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_alumno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='id_tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
