# Generated by Django 5.0 on 2024-01-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coordinacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre: ')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo: ')),
                ('coordinador', models.CharField(max_length=120, verbose_name='Coordinador: ')),
            ],
        ),
    ]
